require_relative '../OpenTokSDKVersion'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13'
use_frameworks!

target 'Video-Transformers' do
 pod 'OTXCFramework', OpenTokSDKVersion
end
